### PR TITLE
Add a new repo for the Jekyll sources of the website

### PR DESCRIPTION
**Pull request by pcdavid**
Also do some cleanup.

### CODE REVIEW

**Comment by netomi** [comment]
shall we go ahead with this new repo or do you try to do it in the same repo with different branches?

**Comment by pcdavid** [comment]
New repo please.

**Review by netomi — APPROVED** [review]

**Comment by pcdavid** [comment]
It looks like I can't push, or even create PRs on the new repo.
Did I miss something?
I use the same clone URL format (`url = git@github.com:eclipse-sirius/sirius-website-sources.git`) and the same identify (`user.name` and `user.email`) as for e.g. `git@github.com:eclipse-sirius/sirius-website.git`.

**Comment by pcdavid** [comment]
Trying the edit the README directly from the GitHub website gives me:

> Sorry, you’re not able to edit this repository directly—you need to fork it and propose your changes from there instead.

Which is not the case for other repos in the org.

**Comment by netomi** [comment]
the permissions are not yet setup. The script runs approx. every 2h. But you can fork the repo already an open a PR.

**Comment by pcdavid** [comment]
OK, I see. I can wait. Thanks for the response.

**Pull request merged**
